sonar.projectKey=mkv-mkverma_Angular-22-machine-coding
sonar.projectName=Angular-22-machine-coding
sonar.organization=mkv-mkverma

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/Angular-22-machine-coding/lcov.info